# Secret Manager Configuration
# This file contains SECRET IDs (not secret values!) - safe to commit to git
#
# USER ACTION REQUIRED:
# Create these secrets in GCP Secret Manager and fill with actual values:
# https://console.cloud.google.com/security/secret-manager?project=zabicekiosk

project_id: zabicekiosk
region: europe-west3

secrets:
  # GitHub Token for PR comments and task commits
  # Create token: https://github.com/settings/tokens/new?scopes=repo&description=cicd-monitor
  github_token:
    name: cicd-monitor-github-token
    description: "GitHub Personal Access Token for cicd-monitor (scope: repo)"
    required_scopes:
      - repo
    usage:
      - "Post PR comments"
      - "Commit task files to .backlog/pending/"
      - "Read PR context"

  # Claude API Key for AI error analysis
  # Create key: https://console.anthropic.com/settings/keys
  anthropic_api_key:
    name: cicd-monitor-anthropic-api-key
    description: "Anthropic Claude API key for error analysis"
    model: claude-3-5-sonnet-20241022
    usage:
      - "Analyze build failures"
      - "Generate root cause analysis"
      - "Suggest fixes"

  # GCP Service Account Key (Cloud Admin)
  # Create key: https://console.cloud.google.com/iam-admin/serviceaccounts?project=zabicekiosk
  gcp_credentials:
    name: cicd-monitor-gcp-credentials
    description: "Service account key for cicd-monitor with Cloud Admin permissions"
    service_account: cicd-monitor@zabicekiosk.iam.gserviceaccount.com
    roles:
      - cloudbuild.builds.editor
      - logging.admin
      - pubsub.admin
      - secretmanager.admin
      - iam.securityAdmin
      - iam.serviceAccountAdmin
      - run.admin
      - compute.instanceAdmin.v1
      - storage.admin
      - monitoring.metricWriter
    usage:
      - "Provision infrastructure resources"
      - "Read build logs"
      - "Create Pub/Sub subscriptions"
      - "Manage secrets"
      - "Grant IAM permissions"

# Access Control
# These service accounts need secretAccessor role on all secrets
accessors:
  - serviceAccount:120039745928@cloudbuild.gserviceaccount.com  # Cloud Build SA
  - serviceAccount:cicd-monitor@zabicekiosk.iam.gserviceaccount.com  # cicd-monitor SA

# Verification Commands
verification:
  list_secrets: gcloud secrets list --project=zabicekiosk --filter="name~cicd-monitor"
  test_github: gcloud secrets versions access latest --secret=cicd-monitor-github-token --project=zabicekiosk
  test_claude: gcloud secrets versions access latest --secret=cicd-monitor-anthropic-api-key --project=zabicekiosk
  test_gcp: |
    gcloud secrets versions access latest --secret=cicd-monitor-gcp-credentials --project=zabicekiosk > /tmp/test.json
    gcloud auth activate-service-account --key-file=/tmp/test.json
    gcloud projects describe zabicekiosk
    rm /tmp/test.json

# Quick Setup Script
# Run this after creating secrets in GCP Console:
setup_commands: |
  # Grant access to Cloud Build service account
  for secret in cicd-monitor-github-token cicd-monitor-anthropic-api-key cicd-monitor-gcp-credentials; do
    gcloud secrets add-iam-policy-binding $secret \
      --member="serviceAccount:120039745928@cloudbuild.gserviceaccount.com" \
      --role="roles/secretmanager.secretAccessor" \
      --project=zabicekiosk
  done

  echo "✅ Secrets configured"
  echo "Run verification: gcloud secrets list --project=zabicekiosk"
