steps:
  - id: enable-firestore-api
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: bash
    args:
      - -c
      - |
        gcloud services enable firestore.googleapis.com

  - id: build-and-deploy-core-api
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run deploy core-api \
          --source services/core-api \
          --region $_REGION \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars GOOGLE_CLOUD_PROJECT=$PROJECT_ID,FIRESTORE_DATABASE_ID=$_FIRESTORE_DATABASE_ID

  - id: build-and-deploy-booking-api
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run deploy booking-api \
          --source services/booking-api \
          --region $_REGION \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars GOOGLE_CLOUD_PROJECT=$PROJECT_ID,FIRESTORE_DATABASE_ID=$_FIRESTORE_DATABASE_ID

  - id: build-kiosk-web
    name: node:20
    entrypoint: npm
    dir: web/kiosk-pwa
    args: ['ci']

  - id: build-kiosk-web-build
    name: node:20
    entrypoint: npm
    dir: web/kiosk-pwa
    args: ['run', 'build']

  - id: build-admin-web
    name: node:20
    entrypoint: npm
    dir: web/admin-portal
    args: ['ci']

  - id: build-admin-web-build
    name: node:20
    entrypoint: npm
    dir: web/admin-portal
    args: ['run', 'build']

  - id: deploy-web
    name: node:20
    entrypoint: bash
    args:
      - -c
      - |
        npm install -g firebase-tools
        firebase deploy --project $PROJECT_ID --only hosting:kiosk,hosting:admin

options:
  logging: CLOUD_LOGGING_ONLY       # или NONE
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET

substitutions:
  _REGION: europe-west3
  _FIRESTORE_DATABASE_ID: "zabicedb"
