steps:
  - id: build-and-deploy-core-api
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run deploy core-api \
          --source services/core-api \
          --region $_REGION \
          --platform managed \
          --allow-unauthenticated

  - id: build-and-deploy-booking-api
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run deploy booking-api \
          --source services/booking-api \
          --region $_REGION \
          --platform managed \
          --allow-unauthenticated

options:
  logging: CLOUD_LOGGING_ONLY       # или NONE
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET

substitutions:
  _REGION: europe-west3
