steps:
  - id: cancel-previous-builds
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: bash
    args:
      - -c
      - |
        gcloud builds list --ongoing --filter 'tags="zabicekiosk"' --format='value(id)' \
        | grep -v "$BUILD_ID" \
        | xargs -r gcloud builds cancel

  - id: enable-firestore-api
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: bash
    args:
      - -c
      - |
        gcloud services enable firestore.googleapis.com

  - id: build-and-deploy-core-api
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run deploy core-api \
          --source services/core-api \
          --region $_REGION \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars GOOGLE_CLOUD_PROJECT=$PROJECT_ID,FIRESTORE_DATABASE_ID=$_FIRESTORE_DATABASE_ID

  - id: build-and-deploy-booking-api
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run deploy booking-api \
          --source services/booking-api \
          --region $_REGION \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars GOOGLE_CLOUD_PROJECT=$PROJECT_ID,FIRESTORE_DATABASE_ID=$_FIRESTORE_DATABASE_ID

  - id: build-zabice-kiosk-web
    name: node:20
    entrypoint: npm
    dir: web/kiosk-pwa
    args: ['ci']

  - id: build-zabice-kiosk-web-build
    name: node:20
    entrypoint: npm
    dir: web/kiosk-pwa
    args: ['run', 'build']

  - id: build-zabice-admin-web
    name: node:20
    entrypoint: npm
    dir: web/admin-portal
    args: ['ci']

  - id: build-zabice-admin-web-build
    name: node:20
    entrypoint: npm
    dir: web/admin-portal
    args: ['run', 'build']

  - id: build-zabice-parent-web
    name: node:20
    entrypoint: npm
    dir: web/parent-web
    args: ['ci']

  - id: build-zabice-parent-web-build
    name: node:20
    entrypoint: npm
    dir: web/parent-web
    args: ['run', 'build']

  - id: deploy-web
    name: node:20
    entrypoint: bash
    args:
      - -c
      - |
        npm install -g firebase-tools
        firebase hosting:sites:create zabice-kiosk-web --project $PROJECT_ID || true
        firebase hosting:sites:create zabice-admin-web --project $PROJECT_ID || true
        firebase hosting:sites:create zabice-parent-web --project $PROJECT_ID || true
        firebase deploy --project $PROJECT_ID --only hosting:kiosk,hosting:admin,hosting:parent

options:
  logging: CLOUD_LOGGING_ONLY       # или NONE
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET

substitutions:
  _REGION: europe-west3
  _FIRESTORE_DATABASE_ID: "zabicedb"

tags:
  - zabicekiosk
