steps:
  - id: enable-firestore-api
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: bash
    args:
      - -c
      - |
        gcloud services enable firestore.googleapis.com
  - id: build-and-deploy-core-api
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run deploy core-api \
          --source services/core-api \
          --region $_REGION \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars GOOGLE_CLOUD_PROJECT=$PROJECT_ID,FIRESTORE_DATABASE_ID=$_FIRESTORE_DATABASE_ID

  - id: build-and-deploy-booking-api
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run deploy booking-api \
          --source services/booking-api \
          --region $_REGION \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars GOOGLE_CLOUD_PROJECT=$PROJECT_ID,FIRESTORE_DATABASE_ID=$_FIRESTORE_DATABASE_ID

options:
  logging: CLOUD_LOGGING_ONLY       # или NONE
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET

substitutions:
  _REGION: europe-west3
  _FIRESTORE_DATABASE_ID: "(default)"
