availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/token-secret/versions/latest
      env: 'TOKEN_SECRET'

steps:
  - id: cancel-previous-builds
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: bash
    args:
      - -c
      - |
        gcloud builds list --ongoing --filter 'tags="zabicekiosk"' --format='value(id)' \
        | grep -v "$BUILD_ID" \
        | xargs -r gcloud builds cancel

  - id: enable-firestore-api
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: bash
    args:
      - -c
      - |
        gcloud services enable firestore.googleapis.com

  # ============================================================
  # QUALITY GATES - Core API
  # ============================================================
  - id: quality-gate-core-api-install
    name: node:20
    entrypoint: npm
    dir: services/core-api
    args: ['ci']

  - id: quality-gate-core-api-lint
    name: node:20
    entrypoint: npm
    dir: services/core-api
    args: ['run', 'lint']
    waitFor: ['quality-gate-core-api-install']

  - id: quality-gate-core-api-typecheck
    name: node:20
    entrypoint: npm
    dir: services/core-api
    args: ['run', 'typecheck']
    waitFor: ['quality-gate-core-api-install']

  - id: quality-gate-core-api-test
    name: node:20
    entrypoint: npm
    dir: services/core-api
    args: ['test', '--', '--coverage', '--passWithNoTests']
    env:
      - 'CI=true'
    waitFor: ['quality-gate-core-api-install']

  - id: quality-gate-core-api-build
    name: node:20
    entrypoint: npm
    dir: services/core-api
    args: ['run', 'build']
    waitFor: ['quality-gate-core-api-lint', 'quality-gate-core-api-typecheck', 'quality-gate-core-api-test']

  # ============================================================
  # QUALITY GATES - Booking API
  # ============================================================
  - id: quality-gate-booking-api-install
    name: node:20
    entrypoint: npm
    dir: services/booking-api
    args: ['ci']

  - id: quality-gate-booking-api-lint
    name: node:20
    entrypoint: npm
    dir: services/booking-api
    args: ['run', 'lint']
    waitFor: ['quality-gate-booking-api-install']

  - id: quality-gate-booking-api-typecheck
    name: node:20
    entrypoint: npm
    dir: services/booking-api
    args: ['run', 'typecheck']
    waitFor: ['quality-gate-booking-api-install']

  - id: quality-gate-booking-api-test
    name: node:20
    entrypoint: npm
    dir: services/booking-api
    args: ['test', '--', '--coverage', '--passWithNoTests']
    env:
      - 'CI=true'
    waitFor: ['quality-gate-booking-api-install']

  - id: quality-gate-booking-api-build
    name: node:20
    entrypoint: npm
    dir: services/booking-api
    args: ['run', 'build']
    waitFor: ['quality-gate-booking-api-lint', 'quality-gate-booking-api-typecheck', 'quality-gate-booking-api-test']

  # ============================================================
  # QUALITY GATES - Admin Portal
  # ============================================================
  - id: quality-gate-admin-portal-install
    name: node:20
    entrypoint: npm
    dir: web/admin-portal
    args: ['ci']

  - id: quality-gate-admin-portal-lint
    name: node:20
    entrypoint: npm
    dir: web/admin-portal
    args: ['run', 'lint']
    waitFor: ['quality-gate-admin-portal-install']

  - id: quality-gate-admin-portal-typecheck
    name: node:20
    entrypoint: npm
    dir: web/admin-portal
    args: ['run', 'typecheck']
    waitFor: ['quality-gate-admin-portal-install']

  - id: quality-gate-admin-portal-test
    name: node:20
    entrypoint: npm
    dir: web/admin-portal
    args: ['test', '--', '--coverage', '--passWithNoTests']
    env:
      - 'CI=true'
    waitFor: ['quality-gate-admin-portal-install']

  # ============================================================
  # QUALITY GATES - Kiosk PWA
  # ============================================================
  - id: quality-gate-kiosk-pwa-install
    name: node:20
    entrypoint: npm
    dir: web/kiosk-pwa
    args: ['ci']

  - id: quality-gate-kiosk-pwa-lint
    name: node:20
    entrypoint: npm
    dir: web/kiosk-pwa
    args: ['run', 'lint']
    waitFor: ['quality-gate-kiosk-pwa-install']

  - id: quality-gate-kiosk-pwa-typecheck
    name: node:20
    entrypoint: npm
    dir: web/kiosk-pwa
    args: ['run', 'typecheck']
    waitFor: ['quality-gate-kiosk-pwa-install']

  - id: quality-gate-kiosk-pwa-test
    name: node:20
    entrypoint: npm
    dir: web/kiosk-pwa
    args: ['test', '--', '--coverage', '--passWithNoTests']
    env:
      - 'CI=true'
    waitFor: ['quality-gate-kiosk-pwa-install']

  # ============================================================
  # QUALITY GATES - Parent Web
  # ============================================================
  - id: quality-gate-parent-web-install
    name: node:20
    entrypoint: npm
    dir: web/parent-web
    args: ['ci']

  - id: quality-gate-parent-web-lint
    name: node:20
    entrypoint: npm
    dir: web/parent-web
    args: ['run', 'lint']
    waitFor: ['quality-gate-parent-web-install']

  - id: quality-gate-parent-web-typecheck
    name: node:20
    entrypoint: npm
    dir: web/parent-web
    args: ['run', 'typecheck']
    waitFor: ['quality-gate-parent-web-install']

  - id: quality-gate-parent-web-test
    name: node:20
    entrypoint: npm
    dir: web/parent-web
    args: ['test', '--', '--coverage', '--passWithNoTests']
    env:
      - 'CI=true'
    waitFor: ['quality-gate-parent-web-install']

  # ============================================================
  # DATABASE VERIFICATION (Before deployment)
  # ============================================================
  - id: verify-database-integrity
    name: node:20
    entrypoint: bash
    dir: services/core-api
    args:
      - -c
      - |
        echo "📦 Ensuring dependencies are installed for verification..."
        npm ci

        echo "🔍 Verifying database integrity before deployment..."
        export GOOGLE_CLOUD_PROJECT=$PROJECT_ID
        export FIRESTORE_DATABASE_ID=$_FIRESTORE_DATABASE_ID
        npm run verify:data-integrity

        if [ $? -ne 0 ]; then
          echo "❌ Database verification FAILED!"
          echo "Critical issues found. Blocking deployment."
          exit 1
        fi

        echo "✅ Database verification PASSED - deployment can proceed"
    waitFor: ['quality-gate-core-api-build']

  # ============================================================
  # DEPLOYMENT - Core API (Only after quality gates pass)
  # ============================================================
  - id: build-and-deploy-core-api
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run deploy core-api \
          --source services/core-api \
          --region $_REGION \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars GOOGLE_CLOUD_PROJECT=$PROJECT_ID,FIRESTORE_DATABASE_ID=$_FIRESTORE_DATABASE_ID
    waitFor: ['quality-gate-core-api-build', 'verify-database-integrity']

  # ============================================================
  # DEPLOYMENT - Booking API (Only after quality gates pass)
  # ============================================================
  - id: build-and-deploy-booking-api
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run deploy booking-api \
          --source services/booking-api \
          --region $_REGION \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars GOOGLE_CLOUD_PROJECT=$PROJECT_ID,FIRESTORE_DATABASE_ID=$_FIRESTORE_DATABASE_ID
    waitFor: ['quality-gate-booking-api-build']

  # ============================================================
  # WEB BUILDS - Kiosk PWA (Only after quality gates pass)
  # ============================================================
  - id: build-zabice-kiosk-web-build
    name: node:20
    entrypoint: npm
    dir: web/kiosk-pwa
    args: ['run', 'build']
    waitFor: ['quality-gate-kiosk-pwa-install', 'quality-gate-kiosk-pwa-lint', 'quality-gate-kiosk-pwa-typecheck', 'quality-gate-kiosk-pwa-test']

  # ============================================================
  # WEB BUILDS - Admin Portal (Only after quality gates pass)
  # ============================================================
  - id: fetch-firebase-api-key
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: bash
    args:
      - -c
      - |
        gcloud secrets versions access projects/120039745928/secrets/zabicekiosk_firebase_api_key/versions/1 > /workspace/firebase_api_key.txt

  - id: build-zabice-admin-web-build
    name: node:20
    entrypoint: bash
    dir: web/admin-portal
    args:
      - -c
      - |
        export VITE_FIREBASE_API_KEY=$(cat /workspace/firebase_api_key.txt)
        npm run build
    waitFor: ['fetch-firebase-api-key', 'quality-gate-admin-portal-install', 'quality-gate-admin-portal-lint', 'quality-gate-admin-portal-typecheck', 'quality-gate-admin-portal-test']

  # ============================================================
  # WEB BUILDS - Parent Web (Only after quality gates pass)
  # ============================================================
  - id: build-zabice-parent-web-build
    name: node:20
    entrypoint: npm
    dir: web/parent-web
    args: ['run', 'build']
    waitFor: ['quality-gate-parent-web-install', 'quality-gate-parent-web-lint', 'quality-gate-parent-web-typecheck', 'quality-gate-parent-web-test']

  # ============================================================
  # DEPLOYMENT - Web Apps (Only after all builds complete)
  # ============================================================
  - id: deploy-web
    name: node:20
    entrypoint: bash
    args:
      - -c
      - |
        npm install -g firebase-tools
        firebase hosting:sites:create zabice-kiosk-web --project $PROJECT_ID || true
        firebase hosting:sites:create zabice-admin-web --project $PROJECT_ID || true
        firebase hosting:sites:create zabice-parent-web --project $PROJECT_ID || true
        firebase deploy --project $PROJECT_ID --only hosting:kiosk,hosting:admin,hosting:parent

  # ============================================================
  # DATABASE MIGRATION (After deployment)
  # ============================================================
  - id: migrate-database-post-deployment
    name: node:20
    entrypoint: bash
    dir: services/core-api
    secretEnv: ['TOKEN_SECRET']
    args:
      - -c
      - |
        echo "🔧 Running database migration (post-deployment)..."
        export GOOGLE_CLOUD_PROJECT=$PROJECT_ID
        export FIRESTORE_DATABASE_ID=$_FIRESTORE_DATABASE_ID

        # Run repair script to optimize searchTokens and fix inconsistencies
        npm run repair:data-integrity

        echo ""
        echo "🔍 Re-verifying database integrity after migration..."
        npm run verify:data-integrity

        if [ $? -ne 0 ]; then
          echo "⚠️  Post-migration verification failed!"
          echo "Database may have inconsistencies - manual review recommended."
          # Don't fail the build, but log warning
          exit 0
        else
          echo "✅ Database migration completed successfully"
        fi
    waitFor: ['build-and-deploy-core-api']

options:
  logging: CLOUD_LOGGING_ONLY       # или NONE
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET

substitutions:
  _REGION: europe-west3
  _FIRESTORE_DATABASE_ID: "zabicedb"

tags:
  - zabicekiosk
