openapi: 3.0.0
info:
  title: core-api
  version: 0.1.0
paths:
  /api/v1/redeem:
    post:
      summary: Redeem pass or record drop-in
      responses:
        '200':
          description: OK
  /api/v1/card:
    get:
      summary: Get public card info
      parameters:
        - in: query
          name: token
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  childName:
                    type: string
                  planSize:
                    type: integer
                  used:
                    type: integer
                  remaining:
                    type: integer
                  expiresAt:
                    type: string
                    format: date-time
  /api/v1/content/active:
    get:
      summary: Get active promo content
      responses:
        '200':
          description: OK
  /api/v1/admin/settings:
    get:
      summary: Get global settings
      responses:
        '200':
          description: OK
    put:
      summary: Update global settings
      responses:
        '200':
          description: OK
  /api/v1/admin/content:
    get:
      summary: List promo content
      responses:
        '200':
          description: OK
    post:
      summary: Create promo content item
      responses:
        '200':
          description: OK
  /api/v1/admin/content/{id}:
    patch:
      summary: Update promo content item
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
  /api/v1/admin/stats:
    get:
      summary: Get dashboard statistics
      responses:
        '200':
          description: OK
