openapi: 3.0.0
info:
  title: core-api
  version: 0.1.0
paths:
  /api/v1/redeem:
    post:
      summary: Redeem pass or record drop-in
      responses:
        '200':
          description: OK
  /api/v1/card:
    get:
      summary: Get public card info
      parameters:
        - in: query
          name: token
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
